let num1 = Number("5");
let num2 = Number("-1");
let num3 = Number("Hello");
document.write(num1+"<br>");
document.write(num2+"<br>");
document.write(num3+"<br>");
let str1 = String(55);
let str2 = String(-10);
let str3 = String(0);
document.write("<br>");
document.write(str1+"<br>");
document.write(str2+"<br>");
document.write(str3+"<br>");
